// Base de données des agents - Export depuis Python CleanCo
window.agentsData = [
    // Groupe A
    {"code": "CPA", "nom": "OUKHA", "prenom": "NABIL", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "CONA", "nom": "EL JAMALI", "prenom": "Younes", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "MOTA", "nom": "TISSIRT", "prenom": "hakim", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "ZA", "nom": "DRAFA", "prenom": "Noureddine", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z2A", "nom": "KAROUCHE", "prenom": "Fayçal", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z5A", "nom": "LAWRIQAT TARIK", "prenom": "TARIK", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O1aA", "nom": "ALAMI", "prenom": "ZAKARIA", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O1bA", "nom": "EL KADMIRI", "prenom": "YASSINE", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O3A", "nom": "EL GHALLA", "prenom": "ABDELALI", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O8A", "nom": "AIT LMKADAM", "prenom": "KAHCEN", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O9A", "nom": "OUTANOUT", "prenom": "OMAR", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O10A", "nom": "ZOUHRI", "prenom": "HAMID", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O11A", "nom": "ARRADI", "prenom": "TARIK", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O12A", "nom": "BOULAHFA", "prenom": "MOHAMED", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O13A", "nom": "ZDIHRI", "prenom": "ABDERRAHIM", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O15A", "nom": "AIT BENALI", "prenom": "ABLKRIM", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O16A", "nom": "HOUMMAY MEHDI", "prenom": "MEHDI", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L2A", "nom": "OUSSALLEM", "prenom": "KHALID", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L5A", "nom": "SLYI", "prenom": "MOHAMED", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L6A", "nom": "KHTIDAK", "prenom": "HICHAM", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L7A", "nom": "ECHOUHAIDI", "prenom": "RACHID", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L8A", "nom": "ABOUKAL", "prenom": "SAID", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L11A", "nom": "QOTBI", "prenom": "OTMAN", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L13A", "nom": "ZEHDI", "prenom": "SALEM", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L14A", "nom": "BOUNHAR", "prenom": "MOHAMED", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L15A", "nom": "BOUCHRIHA", "prenom": "MOUNIR", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L16A", "nom": "ROUANI", "prenom": "AYOUB", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L18A", "nom": "EL KAHLAOUI", "prenom": "ABDELLAH", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L20A", "nom": "FOZARI", "prenom": "ABDLILAH", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    
    // Groupe B
    {"code": "CPB", "nom": "CHMAREKH", "prenom": "Noureddine", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "CONB", "nom": "IBRAHIMY", "prenom": "ABDELLAHADIB", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "MOTB", "nom": "KAALI", "prenom": "MAJID", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "ZB", "nom": "SNAIDA", "prenom": "AHMED", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z2B", "nom": "TSOULI", "prenom": "ADIL", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z5B", "nom": "KAMOUN", "prenom": "YOUNES", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z6B", "nom": "ROCHDI", "prenom": "HASSAN", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O1aB", "nom": "JELOULI", "prenom": "MAROUAN", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O1bB", "nom": "KADI", "prenom": "ANNOUAR", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O3B", "nom": "EL FADEL", "prenom": "MOHAMED", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O4A", "nom": "BOUAKRA", "prenom": "ABDELHAK", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O5B", "nom": "HOUCINE", "prenom": "ASGHEN", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O8B", "nom": "RIFKI", "prenom": "KAMAL", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O9B", "nom": "HADIR", "prenom": "HAKIM", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O10B", "nom": "BELASRI", "prenom": "MOHAMED", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O11B", "nom": "MANSOURI", "prenom": "OUSSAAMA", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O12B", "nom": "LAHYANE", "prenom": "MOHCINE", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O13B", "nom": "ABDOUSSI", "prenom": "HASSAN", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O14B", "nom": "ABEID", "prenom": "MOHAMED", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O15B", "nom": "FAKHAR", "prenom": "ABDEHADI", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O16B", "nom": "NAIM", "prenom": "TAOUFIK", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L2B", "nom": "ZAHI", "prenom": "MOHAMED", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L4B", "nom": "KHODAYRA", "prenom": "YOUNES", "groupe": "A", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L5B", "nom": "BELAHMAR", "prenom": "MOHAMED", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L6B", "nom": "RACHAD", "prenom": "YOUSSEF", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L7B", "nom": "KADDAR", "prenom": "ANOUAR", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L8B", "nom": "OUHADI", "prenom": "AHMED", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L9B", "nom": "EL HAMROUCHI", "prenom": "BOUZIANE", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L10B", "nom": "AKRAOUI", "prenom": "ABDELHAK", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L11B", "nom": "NOUASSI", "prenom": "AHMED", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L13B", "nom": "DAOU", "prenom": "RACHID", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L14B", "nom": "KANOUBI", "prenom": "ABDELGHANI", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L15B", "nom": "BOUTJADIR", "prenom": "HAMZA", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L16B", "nom": "TAOUZI", "prenom": "NOUREDDINE", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L18B", "nom": "SAKANI", "prenom": "ABDELAZIZ", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L20B", "nom": "SAID", "prenom": "RACHAKHA", "groupe": "B", "date_entree": "2025-11-01", "statut": "actif"},
    
    // Groupe C
    {"code": "CPC", "nom": "BERRIMA", "prenom": "ABDELHAK", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "CONC", "nom": "NOUR", "prenom": "HICHAM", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "MOTC", "nom": "IDRISSI", "prenom": "IDRISS", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z6C", "nom": "HARBIL", "prenom": "ANASS", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z2C", "nom": "GRINEH", "prenom": "KHALID", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z5C", "nom": "MULouANI", "prenom": "MUSTAPHA", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O1aC", "nom": "ELKERRAOUI", "prenom": "JAOUAD", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O1bC", "nom": "CHOUKAIRI", "prenom": "AZIZ", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O3C", "nom": "MAKAN", "prenom": "YOUNESS", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O4C", "nom": "HMIJAN", "prenom": "BRAHIM", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O5C", "nom": "ATTOUMI", "prenom": "YOUSSEF", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O8C", "nom": "TAOUFIKI", "prenom": "TOUFIQ", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O9C", "nom": "ELYOUSSFI", "prenom": "MOHAMED", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O10C", "nom": "KHTIDAK", "prenom": "MOHAMED", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O11C", "nom": "ARIBATE", "prenom": "MUSTAPHA", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O13C", "nom": "SAIB", "prenom": "HAMID", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O14C", "nom": "ALOUI", "prenom": "RACHID", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O15C", "nom": "ZOURAKI", "prenom": "YOUSSEF", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O16C", "nom": "ENNABAL", "prenom": "AZOUZ", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L2C", "nom": "ELHILALI", "prenom": "AKRAM", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L4C", "nom": "MAGHAT", "prenom": "RACHID", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L5C", "nom": "FAKUHI", "prenom": "ABDERRAHIL", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L6C", "nom": "RACHID", "prenom": "NOUR", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L7C", "nom": "NAZIR", "prenom": "MOHAMED", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L8C", "nom": "ASSLOUH", "prenom": "HASSAN", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L9C", "nom": "IKHLOUFEN", "prenom": "MOUNIR", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L10C", "nom": "BENGHANMI", "prenom": "DRISS", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L11C", "nom": "LKWISSI", "prenom": "LARBI", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L13C", "nom": "TABTI", "prenom": "ABDELLAH", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L14C", "nom": "ABDEMOUNIM", "prenom": "MNAM", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L15C", "nom": "ALHAFID", "prenom": "TOUFIK", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L16C", "nom": "ELALOUSSI", "prenom": "AZIZ", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L18C", "nom": "SAKANI", "prenom": "ABDELAZIZ", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L20C", "nom": "FARASSI", "prenom": "KARIM", "groupe": "C", "date_entree": "2025-11-01", "statut": "actif"},
    
    // Groupe D
    {"code": "CPD", "nom": "YAGOUB", "prenom": "mouhcine", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "COND", "nom": "ALAHYANE", "prenom": "HOUSSAIN", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "MOTD", "nom": "ALAMI", "prenom": "LAHCEN", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "ZD", "nom": "mehdi", "prenom": "MOULZY", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z2D", "nom": "BOUTSON", "prenom": "MUSTAPHA", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z5D", "nom": "MAHDAD", "prenom": "AYOUB", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z6D", "nom": "ZEROUAL", "prenom": "ABDELHAQ", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O1aD", "nom": "BEN KHADRA", "prenom": "IMAD", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O1bD", "nom": "HADARBACH", "prenom": "KHLIFI", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O3D", "nom": "ABARKAN", "prenom": "YAHYA", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "NO4D", "nom": "KABDANI", "prenom": "MOHAMED", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O8D", "nom": "EL KABOURI", "prenom": "LAHCEN", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O9D", "nom": "HADDIR", "prenom": "HAKIM", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O10D", "nom": "LOURIGHI", "prenom": "ADIL", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O11D", "nom": "HAJJI", "prenom": "TOUFIK", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O12D", "nom": "TOUNSSI", "prenom": "HASSAN", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O13D", "nom": "CHAMI", "prenom": "HASSAN", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O14D", "nom": "OUGHIL", "prenom": "MUSTAPHA", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O15D", "nom": "MACHHAB", "prenom": "ABDERAHIM", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "O16D", "nom": "BOULDGAG", "prenom": "D", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L2D", "nom": "HANSALI", "prenom": "MOLAY AHMED", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L4D", "nom": "ERRAISSY", "prenom": "ABDELJALIL", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L5D", "nom": "EL AISSAOUI", "prenom": "MOHMED", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L6D", "nom": "SIYADI", "prenom": "MAJID", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L7D", "nom": "AIT BOURI", "prenom": "HASSAN", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L9D", "nom": "MEROURI", "prenom": "KARIM", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L10D", "nom": "DAHANI", "prenom": "MOHAMED", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L11D", "nom": "LACHGAR", "prenom": "MOHAMED", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L13D", "nom": "EL HILALI", "prenom": "HICHAM", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L14D", "nom": "ELHARBI", "prenom": "MOHAMED", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L15D", "nom": "DAHBI", "prenom": "JALAL", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L16D", "nom": "JABAL", "prenom": "RACHID", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L18D", "nom": "GUARMA", "prenom": "MOHAMED", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "L20D", "nom": "SATANI", "prenom": "BRAHIM", "groupe": "D", "date_entree": "2025-11-01", "statut": "actif"},
    
    // Groupe E (DUÉ)
    {"code": "ACCA", "nom": "CHAJAI", "prenom": "SOUKAINA", "groupe": "E", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "ACCB", "nom": "MAAROUF", "prenom": "NAJAT", "groupe": "E", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z1A", "nom": "FARROUCHE", "prenom": "MILOUD", "groupe": "E", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z1B", "nom": "KHIAR", "prenom": "NOUREDDINE", "groupe": "E", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z4A", "nom": "ECHALLI", "prenom": "KASSEM", "groupe": "E", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z4B", "nom": "OUHADI", "prenom": "LAHCEN", "groupe": "E", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z4C", "nom": "ELFAKHAR", "prenom": "MOHAMED", "groupe": "E", "date_entree": "2025-11-01", "statut": "actif"},
    {"code": "Z4D", "nom": "TAOUIL", "prenom": "KHALID", "groupe": "E", "date_entree": "2025-11-01", "statut": "actif"}
];

console.log(`✅ ${window.agentsData.length} agents chargés depuis data.js`);
